services:
  core-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jproxy-core-proxy
    restart: unless-stopped
    environment:
      CORE_PROXY_ADDR: ":8118"
      CORE_PROXY_MIN_COUNT: "6"
      JPROXY_DB_PATH: "/data/jproxy.db"
      WEB_DIST_PATH: "/app/web-dist"
    ports:
      - "8118:8118"
    volumes:
      - ./database/jproxy.db:/data/jproxy.db
